name: font-manager
base: core20 # the base snap is the execution environment for this snap
version: '0.8.3-git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  A simple font management application for GTK Desktop Environments.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots


apps:
  font-manager:
    command: usr/local/bin/font-manager
    desktop: usr/local/share/applications/org.gnome.FontManager.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/lib/x86_64-linux-gnu/font-manager:$LD_LIBRARY_PATH
    plugs:
      - desktop
      - desktop-legacy

parts:
  font-manager:
    # See 'snapcraft plugins'
    source: https://github.com/FontManager/font-manager.git
    plugin: meson
    build-packages:
      - valac
      - libfontconfig-dev
      - libjson-glib-dev
      - libgtk-3-dev
      - libsqlite3-dev
      - libxml2-dev
      - libsoup2.4-dev
      - libwebkit2gtk-4.0-dev
      - gettext
      - yelp-tools
      - libgirepository1.0-dev
